# Generated by Django 3.2.7 on 2021-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaDriver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOfflineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('driver_current_latitude', models.CharField(max_length=120)),
                ('driver_current_longitude', models.CharField(max_length=120)),
                ('driver_current_address', models.CharField(blank=True, max_length=1120, null=True)),
                ('on_off_status', models.IntegerField()),
                ('driver_vehicle_type_id', models.IntegerField()),
                ('global_vehicle_id', models.IntegerField()),
            ],
        ),
    ]
