# Generated by Django 3.2.7 on 2021-09-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaDriver', '0002_onlineofflinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineofflinemodel',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineofflinemodel',
            name='driver_vehicle_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineofflinemodel',
            name='global_vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineofflinemodel',
            name='on_off_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
