# Generated by Django 3.2.7 on 2021-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaDriver', '0005_biddingrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingrates',
            name='trip_id',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
