# Generated by Django 3.2.7 on 2021-10-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaDriver', '0006_alter_biddingrates_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverratecard',
            name='canceled_trip_limit',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='driverratecard',
            name='canceled_trips',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='driverratecard',
            name='driver_id',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='driverratecard',
            name='max_rate',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='driverratecard',
            name='min_rate',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='driverratecard',
            name='system_rate',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
