# Generated by Django 3.2.7 on 2021-10-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaDriver', '0007_auto_20211006_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineofflinemodel',
            name='is_busy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
