# Generated by Django 3.2.7 on 2021-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=120, null=True)),
                ('rider_name', models.CharField(blank=True, max_length=120, null=True)),
                ('rider_rating', models.CharField(blank=True, max_length=120, null=True)),
                ('api_token', models.CharField(blank=True, max_length=320, null=True)),
                ('login_status', models.IntegerField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
    ]
