# Generated by Django 3.2.7 on 2021-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaRider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderTripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.IntegerField()),
                ('pickup_lat', models.CharField(blank=True, max_length=210, null=True)),
                ('pickup_lng', models.CharField(blank=True, max_length=210, null=True)),
                ('destination_lat', models.CharField(blank=True, max_length=210, null=True)),
                ('destination_lng', models.CharField(blank=True, max_length=210, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=1210, null=True)),
                ('destination_address', models.CharField(blank=True, max_length=1210, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
