# Generated by Django 3.2.7 on 2021-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaRider', '0003_newtripavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtripavailable',
            name='driver_id',
            field=models.IntegerField(),
        ),
    ]
