# Generated by Django 3.2.7 on 2021-10-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoilaRider', '0004_alter_newtripavailable_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreConformTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('rider_pickup_lat', models.CharField(blank=True, max_length=1220, null=True)),
                ('rider_pickup_lng', models.CharField(blank=True, max_length=1220, null=True)),
                ('rider_pickup_address', models.CharField(blank=True, max_length=1210, null=True)),
                ('rider_destination_address', models.CharField(blank=True, max_length=1210, null=True)),
                ('driver_current_latitude', models.CharField(blank=True, max_length=1210, null=True)),
                ('driver_current_longitude', models.CharField(blank=True, max_length=1210, null=True)),
                ('trip_id', models.IntegerField(blank=True, null=True)),
                ('trip_rate', models.IntegerField(blank=True, null=True)),
                ('trip_status', models.IntegerField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
